services:
  anirec:
    container_name: anirec
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./uploads:/app/backend/uploads
    environment:
      - PORT=8080
      - JWT_SECRET=super-duper-hidden-secret! # Add your JWT secret here
      - DEFAULT_MODEL=google/gemini-2.5-flash # RECOMMENDED to change. For best experience, gemini 2.5 flash
      - OPENAI_API_KEY=myapikey # REQUIRED
      - OPENAI_API_ENDPOINT=endpoint # REQUIRED
      - MONGODB_URI=mongodb://root:example@db:27017/
      - NODE_ENV=production
    networks:
      - anirec-network
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      anirec-network:
        aliases:
          - db
networks:
  anirec-network:
    driver: bridge
